before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
#    - go generate ./...
    - gofmt -w ./
    - go-licenses save github.com/jimmale/godynamicdns --save_path="./licenseterms/licenses/"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
archives:
  - replacements:
#      darwin: Darwin
#      linux: linux
#      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms: ## https://goreleaser.com/customization/nfpm/
  -
    id: godynamicdns
    package_name: godynamicdns
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Jim Male
    maintainer: Jim Male
    homepage: https://github.com/jimmale/godynamicdns
    description: A Dynamic DNS Updater in Go
    license: Apache 2.0
    dependencies:
      - ca-certificates
    formats:
      - deb
      - rpm
    version_metadata: git
    section: default
    empty_folders:
      - /var/log/godynamicdns
    contents:
      # Basic file that applies to all packagers
      - src: packaging/godynamicdns.service
        dst: /etc/systemd/system/godynamicdns.service
      # Simple config file
      - src: packaging/exampleconfig.toml
        dst: /etc/godynamicdns/config.toml
        type: config
    scripts:
      preinstall: "packaging/scripts/preinstall.sh"
      postinstall: "packaging/scripts/postinstall.sh"
      preremove: "packaging/scripts/preremove.sh"
      postremove: "packaging/scripts/postremove.sh"
